#!/bin/sh

set -e

case "$1" in
start)
losetup /dev/loop0 /mnt/nfs_scratch/printserver-swapfile.bin
swapon /dev/loop0
;;
stop)
swapoff /dev/loop0
losetup -d /dev/loop0
;;
restart)
swapoff /dev/loop0
swapon /dev/loop0
;;
*)
echo "swap-file-nfs: swap { start | stop | restart }" >&2
exit 1
;;
esac

exit 0
